language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update
  - sudo apt-get install libv8-dev g++ cpp valgrind libxml2-dev -y
  - printf "\n" | pecl install v8js-0.1.3
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script: valgrind --trace-children=yes vendor/bin/phpunit --debug --verbose